#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "MediaBackend.h"
#include "MediaPlayer.h"
#include "MediaTexture.h"
#include "CoreMediaPlayerComponent.generated.h"


/**
 * Central component exposed to Blueprints to control media playback.
 * It uses the default Unreal Engine Media Framework but adheres to the IMediaBackend interface
 * so it can be swapped later if needed.
 */
UCLASS( ClassGroup=(Media), meta=(BlueprintSpawnableComponent) )
class COREMEDIA_API UCoreMediaPlayerComponent : public UActorComponent, public IMediaBackend
{
	GENERATED_BODY()

public:
	UCoreMediaPlayerComponent();

protected:
	virtual void BeginPlay() override;

public:
	virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

	//~ Begin IMediaBackend Interface
	virtual bool OpenUrl(const FString& Url) override;
	virtual void Play() override;
	virtual void Pause() override;
	virtual void Stop() override;
	virtual void Seek(FTimespan Time) override;
	virtual bool IsPlaying() const override;
	virtual bool IsPaused() const override;
	virtual FTimespan GetTime() const override;
	virtual FTimespan GetDuration() const override;
	virtual void SetVolume(float Volume) override;
	//~ End IMediaBackend Interface

	/** Get the texture generated by the media player, useful for hooking into materials */
	UFUNCTION(BlueprintCallable, Category = "Media")
	UMediaTexture* GetMediaTexture() const { return MediaTexture; }

	/** The underlying Unreal Media Player */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Media")
	UMediaPlayer* MediaPlayer;

	/** The texture that displays the video output */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Media")
	UMediaTexture* MediaTexture;

private:
	/** Helper to initialize default media components if not explicitly provided */
	void InitializeDefaultMediaComponents();
};
